language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache
    
before_script:
  - composer self-update
  - composer install --dev --prefer-source

script: 
    - phpunit --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --access-token="your-token" --format=php-clover coverage.clover
